---
# Project information
site_name: SIG/AI Wiki
site_url: https://sig-ai.rocky.page
site_description: >-
  The wiki for the AI Special Interest Group of the Rocky Linux project

# Repository
repo_url: https://git.resf.org/sig_ai/wiki
repo_name: sig_ai/wiki
edit_uri: _edit/main/docs/

#MkDocs site structure
nav:
    - Home: index.md
    - About: 
        - About: about.md
    - Members: 
        - Members: members.md
    - Community: 
        - Community: community.md
        - Partners: community/partners.md
        - Sponsors: community/sponsors.md
    - Contribute: 
        - Contribute: contribute.md
        - Mattermost: contribute/mattermost.md
        - Forums: contribute/forums.md
        - Git: contribute/git.md
    - Docs: 
        - Rocky Linux: docs.md
    - Events: 
        - Events: events.md
        - Upcoming Events: events/upcoming-events.md
        - Highlights: events/highlights.md
        - Past Evetns: events/past-events.md
    - Contact: 
        - Contact: contact.md
        
copyright: Copyright &copy; 2023 Rocky   Enterprise Software Foundation

# Configuration
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/icon-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - bash
    - perl
    - python
    - yaml
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.integrate
    - toc.follow
#    - content.action.edit

# Plugins
plugins:
  - autolinks
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - search
  - tags
  - mkdocs-jupyter

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
